# Workflow temporarily disabled
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - master
# permissions:
#   id-token: write
#   contents: read
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
#       AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
#       AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
#       AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
#       AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}